title: Sandworm
email: TODO@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: TODO
github_username:  TODO

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Just The Docs configuration

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"

# Aux links for the upper right navigation
aux_links:
  "Sandworm on GitHub":
    - "//github.com/mariuszhermansdorfer/SandWorm"

# Footer content appears at the bottom of every page's main content
footer_content: "TODO: Copyright & license details"
